//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package game {
	import com.adamatomic.flixel.*;
	
	public class MapLevel1 extends MapBase {
		//Media content declarations
		[Embed(source="data/MapCSV_Level1_Main.txt", mimeType="application/octet-stream")] public var CSV_Main:Class;
		[Embed(source="data/tiles.png")] public var Img_Main:Class;
		[Embed(source="data/MapCSV_Level1_BackgroundDirt.txt", mimeType="application/octet-stream")] public var CSV_BackgroundDirt:Class;
		[Embed(source="data/tiles_bg.png")] public var Img_BackgroundDirt:Class;
		[Embed(source="data/MapCSV_Level1_BackgroundSky.txt", mimeType="application/octet-stream")] public var CSV_BackgroundSky:Class;
		[Embed(source="data/tiles.png")] public var Img_BackgroundSky:Class;

		
		public function MapLevel1() {

			_setCustomValues();

			bgColor = 0xffc3cde9;

			layerMain = new FlxTilemap(new CSV_Main, Img_Main,1,2);
			layerMain.x = 0;
			layerMain.y = 0;
			layerMain.scrollFactor.x = 1.000000;
			layerMain.scrollFactor.y = 1.000000;
			layerBackgroundDirt = new FlxTilemap(new CSV_BackgroundDirt, Img_BackgroundDirt,0,1);
			layerBackgroundDirt.x = 0;
			layerBackgroundDirt.y = 150;
			layerBackgroundDirt.scrollFactor.x = 0.650000;
			layerBackgroundDirt.scrollFactor.y = 0.800000;
			layerBackgroundSky = new FlxTilemap(new CSV_BackgroundSky, Img_BackgroundSky,0,1);
			layerBackgroundSky.x = 0;
			layerBackgroundSky.y = 0;
			layerBackgroundSky.scrollFactor.x = 0.250000;
			layerBackgroundSky.scrollFactor.y = 1.000000;

			allLayers = [ layerMain, layerBackgroundDirt, layerBackgroundSky ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 800;
			boundsMaxY = 800;
		}

		override public function addSpritesToLayerMain(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new Coin(108, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(140, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(172, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(204, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(364, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(396, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(428, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(460, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(748, 716);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(748, 684);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(748, 652);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(524, 652);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(492, 652);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(460, 652);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(364, 620);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(332, 620);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(236, 588);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(204, 588);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(108, 556);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(428, 524);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(460, 524);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(524, 492);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Coin(556, 492);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function addSpritesToLayerBackgroundSky(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new Player(72, 712);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
